name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Echo
        run: | 
          echo "Hello, world!"
          echo "Hello, There!"
      - name: Print Echo Again
        run: |
          echo "Done"
          echo "Bye"
